#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# scripts/07_emotion_elicited_generation_circuit_based/5_label_circuit_emotion_text.py
"""
对全局电路情绪注入生成的文本进行打标
Label emotion-injected texts generated by global circuit

功能 Functions:
  1. 使用GPT-4o-mini判断生成的文本是否符合目标情绪
     Use GPT-4o-mini to judge if generated text matches target emotion
  2. 对所有极性事件的所有情绪注入文本进行打标
     Label all emotion-injected texts for all valence events
  3. 聚焦于文本风格/语气而非内容效价
     Focus on text style/tone rather than content valence

输入输出 Input/Output:
  - 输入 Input:  outputs/{model_name}/07_emotion_elicited_generation_circuit_based/circuit_steered_generation/circuit_steer_all_valences_outputs.jsonl
  - 输出 Output: outputs/{model_name}/07_emotion_elicited_generation_circuit_based/circuit_steered_generation/labeled/circuit_labels.jsonl
"""

import os, json, argparse, time, math, sys
from pathlib import Path
from typing import Dict, Any

# ============== 路径与基本配置 ==============
# ============== Paths and Basic Configuration ==============
# 项目根目录：自动获取脚本所在位置的上两级目录
# Project root: automatically get the directory two levels up from the script location
PROJECT_ROOT = Path(__file__).resolve().parents[2]
os.chdir(PROJECT_ROOT)

MODEL_NAME = "llama32_3b"
LABELING_MODEL = "gpt-4o-mini"

EMOTIONS = ["anger","sadness","happiness","fear","surprise","disgust"]
VALENCES = ["positive", "neutral", "negative"]

# ============== OpenAI 客户端 ==============
# ============== OpenAI Client ==============
from openai import OpenAI

# 从环境变量读取API key
# Read API key from environment variable
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', None)
if not OPENAI_API_KEY:
    print("警告 Warning: OPENAI_API_KEY 环境变量未设置 not set")
    print("请设置环境变量 Please set: export OPENAI_API_KEY='your-api-key'")

client = OpenAI(api_key=OPENAI_API_KEY)

# ============== Prompt 模板 ==============
# ============== Prompt Templates ==============
SYSTEM = f'''
You are a careful rater. 
Given a target emotion and a text, 
decide if the text's STYLE matches the target emotion among:
{EMOTIONS}
Focus on tone/attitude, not content valence.
'''

USER_TMPL = '''
Target emotion: {emotion}
Text:
{text}
Decide if the text's STYLE matches the target emotion.
Return a compact JSON with keys exactly:
{{
"match": <0 or 1>, 
"reason": <short string>
}}
'''

# ============== GPT 调用 ==============
# ============== GPT Calling ==============
def call_gpt(emotion: str, text: str) -> Dict[str, Any]:
    """
    调用GPT进行情绪匹配判断
    Call GPT to judge emotion matching
    
    参数 Args:
        emotion: 目标情绪 target emotion
        text: 待判断文本 text to judge
    
    返回 Returns: {"match": 0/1, "reason": "..."}
    """
    try:
        response = client.chat.completions.create(
            model=LABELING_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": USER_TMPL.format(emotion=emotion, text=text)}
            ],
            temperature=0.1,
            max_tokens=200
        )
        
        result_text = response.choices[0].message.content.strip()
        
        # 尝试解析JSON
        # Try to parse JSON
        try:
            result = json.loads(result_text)
            if "match" in result and "reason" in result:
                return result
            else:
                return {"match": 0, "reason": "Invalid JSON structure"}
        except json.JSONDecodeError:
            return {"match": 0, "reason": "JSON decode error"}
            
    except Exception as e:
        return {"match": 0, "reason": f"API error: {str(e)}"}

# ============== 记录处理 ==============
# ============== Record Processing ==============
def process_single_record(record: Dict[str, Any]) -> Dict[str, Any]:
    """
    处理单条记录，对所有情绪文本进行打标
    Process single record, label all emotion texts
    
    参数 Args:
        record: 原始记录 original record
    
    返回 Returns: 打标后的记录 labeled record
    """
    print(f"处理中 Processing {record.get('skeleton_id', 'unknown')} - {record.get('theme', 'unknown')}")
    
    result = {
        "skeleton_id": record.get("skeleton_id"),
        "theme": record.get("theme"),
        "scenario": record.get("scenario"),
        "valence_results": {},
        "parameters": record.get("parameters", {}),
        "timestamp": int(time.time()),
        "labeling_info": {
            "model": LABELING_MODEL,
            "system_prompt": SYSTEM,
            "total_emotions": len(EMOTIONS),
            "total_valences": len(VALENCES),
            "total_texts": len(EMOTIONS) * len(VALENCES)
        }
    }
    
    # 处理每个事件极性
    # Process each event valence
    for valence in VALENCES:
        if valence not in record.get("valence_results", {}):
            print(f"  [!] 警告 Warning: {valence} valence not found")
            continue
            
        valence_data = record["valence_results"][valence]
        valence_labels = {}
        
        print(f"  处理 Processing {valence} valence...")
        
        # 对每种情绪进行打标
        # Label each emotion
        for emotion in EMOTIONS:
            if emotion not in valence_data:
                print(f"    [!] 警告 Warning: {emotion} emotion not found in {valence}")
                valence_labels[emotion] = {"match": 0, "reason": "Missing emotion text"}
                continue
                
            text = valence_data[emotion]
            
            # 跳过错误文本
            # Skip error texts
            if isinstance(text, str) and text.startswith("[ERROR]"):
                print(f"    [{emotion}] 跳过错误文本 Skipping error text: {text}")
                valence_labels[emotion] = {"match": 0, "reason": "Error in original generation"}
                continue
            
            print(f"    [{emotion}] 打标中 Labeling...")
            label_result = call_gpt(emotion, text)
            valence_labels[emotion] = label_result
            
            # 显示结果
            # Display result
            match_symbol = "✓" if label_result["match"] == 1 else "✗"
            print(f"      {match_symbol} {label_result['reason']}")
            
            # 添加小延迟避免API限制
            # Add small delay to avoid API rate limits
            time.sleep(0.5)
        
        result["valence_results"][valence] = valence_labels
    
    return result

# ============== 主函数 ==============
# ============== Main Function ==============
def main():
    """
    主函数
    Main function
    """
    ap = argparse.ArgumentParser(description="全局电路情绪文本打标 Global circuit emotion text labeling")
    ap.add_argument("--model_name", type=str, default=MODEL_NAME,
                    help="模型名称 Model name")
    ap.add_argument("--input_filename", type=str, default="circuit_steer_all_valences_outputs.jsonl",
                    help="输入文件名 Input filename")
    ap.add_argument("--output_filename", type=str, default="circuit_labels.jsonl",
                    help="输出文件名 Output filename")
    ap.add_argument("--max_records", type=int, default=None,
                    help="最大处理记录数（用于测试）Max records to process (for testing)")
    args = ap.parse_args()
    
    # 路径配置
    # Path configuration
    base_dir = PROJECT_ROOT / "outputs" / args.model_name / "07_emotion_elicited_generation_circuit_based" / "circuit_steered_generation"
    input_path = base_dir / args.input_filename
    output_dir = base_dir / "labeled"
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / args.output_filename
    
    print(f"\n{'='*70}")
    print(f"全局电路情绪文本打标 Global Circuit Emotion Text Labeling")
    print(f"{'='*70}")
    print(f"[配置 CONFIG]")
    print(f"  - 输入文件 Input file: {input_path}")
    print(f"  - 输出文件 Output file: {output_path}")
    print(f"  - 打标模型 Labeling model: {LABELING_MODEL}")
    print(f"  - 情绪类型 Emotion types: {EMOTIONS}")
    print(f"  - 事件极性 Event valences: {VALENCES}")
    if args.max_records:
        print(f"  - 限制处理 Limit: 前 first {args.max_records} 条记录 records")
    print()
    
    # 检查输入文件
    # Check input file
    if not input_path.exists():
        print(f"[-] 错误 Error: 输入文件不存在 Input file not found: {input_path}")
        print(f"    请先运行 Please run first: 4_circuit_steer_all_valences.py")
        return
    
    # 读取输入数据
    # Read input data
    records = []
    with open(input_path, 'r', encoding='utf-8') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                record = json.loads(line)
                records.append(record)
                if args.max_records and len(records) >= args.max_records:
                    break
            except json.JSONDecodeError as e:
                print(f"[!] 警告 Warning: 第 line {line_num} JSON解析错误 JSON parse error: {e}")
                continue
    
    print(f"[+] 已读取 Read {len(records)} 条记录 records")
    if args.max_records:
        print(f"    (限制处理前 Limited to first {args.max_records} 条 records)")
    print()
    
    # 处理记录
    # Process records
    start_time = time.time()
    processed_count = 0
    
    with open(output_path, 'w', encoding='utf-8') as f:
        for i, record in enumerate(records):
            try:
                print(f"[{i+1}/{len(records)}] ", end="")
                labeled_record = process_single_record(record)
                
                # 保存结果
                # Save result
                f.write(json.dumps(labeled_record, ensure_ascii=False) + "\n")
                processed_count += 1
                
                print(f"  [✓] 已保存 SAVED: Record {i+1} saved to {output_path}")
                
                # 每处理5个记录显示进度
                # Show progress every 5 records
                if (i + 1) % 5 == 0:
                    elapsed = time.time() - start_time
                    avg_time = elapsed / (i + 1)
                    remaining = (len(records) - i - 1) * avg_time
                    print(f"[进度 PROGRESS] {i+1}/{len(records)} completed, 耗时 elapsed: {elapsed:.1f}s, 预计剩余 remaining: {remaining:.1f}s")
                
                print()
                
            except Exception as e:
                print(f"  [!] 错误 ERROR: Processing record {i+1} failed: {e}")
                continue
    
    # 统计结果
    # Statistical summary
    total_time = time.time() - start_time
    total_texts = processed_count * len(EMOTIONS) * len(VALENCES)
    
    print(f"\n{'='*70}")
    print(f"[完成] 打标任务完成！[Done] Labeling task completed!")
    print(f"{'='*70}")
    print(f"  处理记录数 Processed records: {processed_count}/{len(records)}")
    print(f"  总文本数 Total texts: {total_texts}")
    print(f"  总耗时 Total time: {total_time:.1f}s")
    print(f"  平均每条记录 Average per record: {total_time/processed_count:.1f}s")
    print(f"  平均每个文本 Average per text: {total_time/total_texts:.2f}s")
    print(f"  结果保存至 Results saved to: {output_path}")
    print(f"{'='*70}\n")

if __name__ == "__main__":
    main()

